### PR TITLE
Forse LF line ending.

### LINKED ISSUE #36: Utils test fails
FAIL: test_canReadLines (test.utils.Lines.test_lines.TestLines)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\veniq\test\utils\Lines\test_lines.py", line 11, in test_canReadLines
    self.assertEqual(
AssertionError: 'class SimpleLinesTest {\n' != 'class SimpleLinesTest {\r\n'
- class SimpleLinesTest {
+ class SimpleLinesTest {
?                        +
 : Did not match first line

### PR DESCRIPTION
**Pull request by aravij**
I suggest to force linux ending style for being able to compare multiline strings on all platforms.

Please check, does it breaks anything in you IDE or text editor.
This should fix #36 and #37

### CODE REVIEW

**Comment by lyriccoder** [comment]
I have the same errors in tests:
```$ python -m unittest discover
.ss..F..........................................FD:\git\veniq\test\utils\test_cfg_builder.py:10: DeprecationWarning: Call to deprecated class JavaPackage. (This functionality must be transmitted to ASTNode)
  java_package = JavaPackage(Path(__file__).parent.absolute() / 'SimpleClass.java')
D:\git\veniq\veniq\ast_framework\java_package.py:32: DeprecationWarning: Call to deprecated class JavaClass. (This functionality must be transmitted to ASTNode)
  java_class = JavaClass(class_ast.tree, class_ast.root, self)
D:\git\veniq\veniq\ast_framework\java_class.py:25: DeprecationWarning: Call to deprecated method children_with_type. (Use ASTNode functionality instead.)
  class_name = next(self.children_with_type(self.root, ASTNodeType.STRING))
D:\git\veniq\veniq\ast_framework\java_class.py:38: DeprecationWarning: Call to deprecated class JavaClassMethod. (This functionality must be transmitted to ASTNode)
  method = JavaClassMethod(method_ast.tree, method_ast.root, self)
D:\git\veniq\veniq\ast_framework\java_class_method.py:24: DeprecationWarning: Call to deprecated method children_with_type. (Use ASTNode functionality instead.)
  method_name = next(self.children_with_type(self.root, ASTNodeType.STRING))
..ssssssssss
======================================================================
FAIL: test_class_computed_fields (test.ast_framework.test_ast_node.ASTNodeTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\veniq\test\ast_framework\test_ast_node.py", line 22, in test_class_computed_fields
    self.assertEqual(java_class.documentation, "/**\n* Some documentation\n*/")
AssertionError: '/**\r\n* Some documentation\r\n*/' != '/**\n* Some documentation\n*/'
- /**
?    -
+ /**
- * Some documentation
?                     -
+ * Some documentation
  */

======================================================================
FAIL: test_canReadLines (test.utils.Lines.test_lines.TestLines)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\veniq\test\utils\Lines\test_lines.py", line 11, in test_canReadLines
    self.assertEqual(
AssertionError: 'class SimpleLinesTest {\n' != 'class SimpleLinesTest {\r\n'
- class SimpleLinesTest {
+ class SimpleLinesTest {
?                        +
 : Did not match first line

----------------------------------------------------------------------
Ran 61 tests in 0.720s

FAILED (failures=2, skipped=12)```

**Comment by lyriccoder** [comment]
I have fixed it. @acheshkov, could you please merge?

**Comment by aravij** [comment]
@lyriccoder  Yes it works for me. What was the problem?

**Comment by lyriccoder** [comment]
I had to set encoding to unix:

```
$ ex SimpleLinesTest.java << EOF
> :set fileformat=unix
> :wq
> EOF
```

**Review by lyriccoder — APPROVED** [review]
ok

**Pull request merged**
